const fuzz = require('fuzzball');
const fs = require('fs')
var json2xls = require('json2xls');
const humanizeDuration = require('humanize-duration')
var uniq = require('lodash/uniq');
var mean = require('lodash/mean');

const words = [
    'shovakar neupane',
    'shovhakar parajuli',
    'shramanel anand',
    'shravan kumar nepali',
    'shrawan kumar agrawal',
    'shrawan kumar g.c',
    'shrawan kumar yadav',
    'shrawankumar agrawal',
    'shree chandra sah',
    'shree kant poudel',
    'shree krishna giri',
    'shree krishna nepal',
    'shree maya lama',
    'shree prasad jawegu',
    'shree prasad mainali',
    'shree prasad saha',
    'shree prasad sanjel',
    'shree ram dhakal',
    'shree ram kamat',
    'shree ram lamichhane',
    'shreedhar gautam',
    'shreedhar rokka',
    'shreedhar sapkota',
    'shreee prasad sah',
    'shreejana sharma',
    'shreekanta poudel',
    'shreekanti passi',
    'shreekrishna bhattarai',
    'shreelal paudel',
    'shreeman kumar gautam',
    'shreemaya thakali',
    'shreenath baral',
    'shreeprasad mainali',
    'shreeprasad shah',
    'shreepurush dhakal',
    'shreeram panta',
    'shreeranjan lakoul',
    'shreprasad jawegu',
    'shreshraj siwakoti',
    'shri dhar sapkota',
    'shri krishna anirudra gautam',
    'shri maya thakali',
    'shri prasad yadav',
    'shridhar sapkota',
    'shrijana sharma',
    'shrijana syaju',
    'shrikanti pashi',
    'shrikhant paudel',
    'shrikumari tharuni',
    'shrilal shah',
    'shrimaya thakali',
    'shriprasad rokka magar',
    'shriram pant',
    'shtya narayan mandal',
    'shubha lal chaudhary mridaha tharu',
    'shubhangud katawal',
    'shubhas chandra shah thakuri',
    'shukra raj sanyog',
    'shukra raj sharma',
    'shushil chandra amatya',
    'shushila karki (subedi)',
    'shushila chaudhary',
    'shushila karki',
    'shushma sharma',
    'shusila kandangwa',
    'shusila nepal',
    'shusila sinkhada',
    'shusila sirpaaili',
    'shusma yadav',
    'shyam bhakta thapa',
    'shyam ji pradhan',
    'shyam krishna bhatarai',
    'shyam kumar adhikari',
    'shyam kumar ghimire',
    'shyam kumar mairata yadav',
    'shyam kumar shrestha',
    'shyam kumari chaudhary',
    'shyam lal rana tharu',
    'shyam pari devi',
    'shyam prasad adhikari',
    'shyam prasad dhakal',
    'shyam prasad ghimire',
    'shyam prasad gupta',
    'shyam prasad lama',
    'shyam prasad poudyal',
    'shyam prasad yadav',
    'shyam shrestha',
    'shyam sundar chaudhari',
    'shyam sundar gupta',
    'shyam sundar kandel',
    'shyam sundar tibadewal',
    'shyam yadav',
    'shyama kumar rajbanshi',
    'shyamdev meheta',
    'shyamkrishna bhattarai',
    'shyamkumar shrestha',
    'shyamlal rana tharu',
    'shyamsundar gupta',
    'siddhant rai',
    'siddharth kumar somani',
    'siddharth maharjan (vikshu nigrodh)',
    'siddhartha koirala',
    'siddhartha somani',
    'siddhartha yadav',
    'siddhi lal shrestha',
    'siddhi lal singh',
    'siddi kumar maharjan',
    'sima kumari bk',
    'sima kumari chetri',
    'sindhu jalesha budhathoki',
    'singa bahadur bishwokarma',
    'singashan sa kalwar',
    'singh bahadur thapa',
    'singh raut',
    'singh yadav',
    'singha bahadur bishwokarma',
    'singha bahadur thapa',
    'siraj a pharuki',
    'siraj ahamad faruki',
    'sirjana taramu khatri',
    'sishir kumar dhungana',
    'sita gurung',
    'sita pokharel',
    'sita adhikari',
    'sita devi boudel',
    'sita devi koirin',
    'sita devi pandey devkota',
    'sita devi thebe (jabegu)',
    'sita devi yadav',
    'sita giri(oli)',
    'sita kumari nepali',
    'sita kumari poudel',
    'sita kumari poudel (adhikari)',
    'sita kumari sundas',
    'sita kumari thakur',
    'sita kumari tharu',
    'sita lama',
    'sita luitel (gyawali)',
    'sita mandal dhanuk',
    'sita nepali',
    'sita poudel',
    'sita ram adhikari',
    'sita ram bhandari',
    'sita ram joshi',
    'sita ram mandal',
    'sita shrestha',
    'sita sundas',
    'sitadevi boudel',
    'sitadevi yadav',
    'sital babu regmi',
    'sital jha',
    'sitaram mahato',
    'sitaram agrawal',
    'sitaram bhandari',
    'sitaram ghimire',
    'sitaram gupta',
    'sitaram joshi',
    'sitaram thapaliya',
    'sitaram uprety',
    'siti giri oli',
    'sivachandra prasad kushwaha',
    'siya ram chaudhary',
    'siyaram prasad kushwaha',
    'siyaram rai',
    'siyaram raya',
    'sjb ranal',
    'smriti narayan chaudhary',
    'sobha lama',
    'sobha shakya',
    'sobhiyat bahadur adhikari',
    'sohan prasad chaudhari',
    'som kumar karki',
    'som lal subedi',
    'som maya tamang',
    'som mishra',
    'som prasad mishra',
    'somlal subedi',
    'somnath pyasi adhikari',
    'somnath sapkota',
    'somprasad pandey',
    'somsak pipoppinyo',
    'sonam chhejung lama',
    'sonam singh syangtan',
    'soniya yadav',
    'sosila shahi',
    'sovha kant poudyal',
    'soyam bahadur khadka',
    'soyam prakash pandit',
    'sramaner anand',
    'srawagyaratna tuladhar',
    'srawajit prasad mahato',
    'srawan kumar agrawal',
    'sri kanti pasi',
    'sri kumar chudal',
    'sri maya thakali',
    'sri prasad jayegu',
    'sri ram dhakal',
    'sri ram paudyal',
    'sri ranjan lakul',
    'sridhar gautam',
    'srijana sayaju',
    'srijana sharma',
    'srijana shrestha',
    'srijana taramu khatri',
    'srikanti pasi',
    'srimaya thakali',
    'sriprasad mukhiya bin',
    'sriram thapa',
    'srish shamsher rana',
    'stanislav i. simakov',
    'stine heiselberg',
    'subamsha yadav',
    'subarna jwarchan',
    'subarna kumar joshi',
    'subarna sumsher',
    'subas karmacharya',
    'subash babu puri',
    'subash chandra dhungel',
    'subash chandra shah thakuri',
    'subash kc',
    'subhan ali ansari',
    'subhas chandra thakuri',
    'subhas karmacharya',
    'subhas raj kafle',
    'subhash chandra nemwang',
    'subhash chandra shah thakuri',
    'subodh kumar pokhrel',
    'subodh kumar pyakurel',
    'subodh prasad gautam',
    'subuna basnet',
    'sudan rai',
    'sudan kirati',
    'sudan shrestha',
    'sudarshan baral',
    'sudarshan prasad nepal',
    'sudarshan raj pandey',
    'sudesh parajuli',
    'sudha sharma',
    'sudha jha',
    'sudhan kirati',
    'sudhir kumar poudel',
    'sudhir kumar shah',
    'sudhir kumar siwakoti',
    'sudhir shah',
    'sudip pathak',
    'sudir kumar siwakoti',
    'sudir prasad shah',
    'sugat ratna kansakar',
    'sugrib paudel',
    'suhila nepal',
    'sujata koirala',
    'sujata pariyar',
    'sujita shakya',
    'suk dev khatri',
    'sukbahadur roka',
    'sukdaiya chaudhari tharu',
    'sukdev bhattrai khatry',
    'sukdev khatri',
    'sukha chandra jha',
    'sukhaya khag',
    'suman kumar shrestha',
    'suman kumari thami',
    'suman meher shrrestha',
    'suman prasad sharma',
    'suman raj pyakural',
    'suman sharma rayamajhi',
    'sumit kumar agarwal',
    'sumitra amatya',
    'sumitra devi raya yadav',
    'sumitra tharuni',
    'sumitradevi rai yadav',
    'sumitratharuni',
    'sun devi joshi',
    'sundar bahadur bishwokarma',
    'sundar thapa chettri',
    'sundevi joshi',
    'sundra tharu',
    'sung do yoon',
    'suni lama',
    'sunil prajapati',
    'sunil babu panta',
    'sunil babu shrestha',
    'sunil bahadur malla',
    'sunil bahadur thapa',
    'sunil kumar manandhar',
    'sunil kumar raya',
    'sunil kumar yadav(jitendra)',
    'sunil manandhar',
    'sunilbabu pant',
    'sunita baral',
    'sunita devi mochi',
    'sunita kumari chaudhary',
    'sunita kumari mahato',
    'sunita kumari thather',
    'sunita kurumbang',
    'sunita poddar',
    'suntalal prasad chaudhary',
    'suntali devi chaudhary',
    'supendra tamrakar',
    'suprabha ghimire',
    'suraj lamichhane',
    'suraj vaidya',
    'surendra pandey',
    'surendra bahadur basnet',
    'surendra bahadur bista',
    'surendra bahadur hamal',
    'surendra bahadur singh',
    'surendra bajracharya',
    'surendra bir singh bashnyat',
    'surendra bist',
    '"surendra chaudhary',
    'surendra jha',
    'surendra k.c',
    'surendra karki',
    'surendra kumar aryal',
    'surendra kumar karki',
    'surendra kumar yadav',
    'surendra lama',
    'surendra man pradhan',
    'surendra manandhar',
    'surendra prakash jabegu',
    'surendra prasad chaudary',
    'surendra prasad chaudhary',
    'surendra prasad jayswal',
    'surendra prasad pandey',
    'surendra prasad poudyal',
    'surendra prasad singh',
    'surendra prasad yadav',
    'surendra raj acharya',
    'surendra raj gossai',
    'surendra raj pandey',
    'surendra singh ayer',
    'surendra thapa',
    'surendra thapa magar',
    'surendra tiwari',
    'suresh acharya',
    'suresh adhikari',
    'suresh chandra chalise',
    'suresh chandra das',
    'suresh khanal',
    'suresh kumar agrawal',
    'suresh kumar alemagar',
    'suresh kumar karki',
    'suresh kumar karna,',
    'suresh kumar khanal',
    'suresh kumar mandal',
    'suresh kumar pudasaini',
    'suresh kumar rai',
    'suresh kumar yongya',
    'suresh man shrestha',
    'suresh mandal',
    'suresh nepal',
    'suresh pradhan',
    'suresh prakash acharya',
    'suresh prasad patel',
    'suresh prasad yadav',
    'suresh raj sharma',
    'suresh raya (gohar)',
    'suresh sekhar bajracharya,',
    'suresh yadav',
    'sureshkumar rai',
    'surita kumari saha',
    'suriyadev das uraw',
    'surja narayan shrestha',
    'suroj pokhrel',
    'survansh kumar chaudhary',
    'surya acharya',
    'surya bahadur k. c.',
    'surya bahadur kc',
    'surya bahadur raut',
    'surya bahadur sen',
    'surya bahadur shahi',
    'surya bahadur thapa',
    'surya bahadursen oli',
    'surya bhadur thapa',
    'surya bhakta pokharel',
    'surya chandra neupane',
    'surya dev das urav',
    'surya dhungel',
    'surya kiran gurung',
    'surya lal yadav',
    'surya maan gurung',
    'surya man dong',
    'surya man dong tamang',
    'surya man gurung',
    'surya man limbu',
    'surya narayan mandal',
    'surya narayan yadav',
    'surya nath mandal',
    'surya nath prasad yadav',
    'surya nath upadhyay',
    'surya prakash wala rai',
    'surya prasad acharya',
    'surya prasad adhikari',
    'surya prasad aryal',
    'surya prasad koirala',
    'surya prasad parajuli',
    'surya prasad pathak',
    'surya prasad pokhrel',
    'surya prasad sharma',
    'surya prasad shrestha',
    'surya prasad silwal',
    'surya raj dhahal',
    'surya silwal',
    'surya thapa',
    'suryabahadur k.c.',
    'suryadev das uraw',
    'suryaman dong tamang',
    'suryanath mandal',
    'suryanath prakash adhikari',
    'suryaprkash subedi',
    'sushil koirala',
    'sushil bhatta',
    'sushil bhattarai',
    'sushil chandra amatya',
    'sushil ghimire',
    'sushil gyawali',
    'sushil jung bahadur rana',
    'sushil kumar aryal',
    'sushil kumar panta',
    'sushil kumar shrestha',
    'sushil kumar thapa',
    'sushil man sherchan',
    'sushil prasad sharma dhungel',
    'sushil shrestha',
    'sushila aryal',
    'sushila budhathoki',
    'sushila chaudhari',
    'sushila karki',
    'sushila koirala',
    'sushila nepal',
    'sushila pahadi',
    'sushila shakya',
    'sushila sharma',
    'sushila shrestha',
    'sushila singh shilu',
    'sushila sirpali thakuri',
    'sushma chaudhary',
    'sushma sharma',
    'sushma yadav',
    'suwarna jwarchan',
    'suwarna shrestha',
    'suwash sundas',
    'suyarma raj rai',
    'swarnim wagle',
    'swayambhu man amatya',
    'swikriti parajuli',
    'syed shah mohammad ali',
    't.p sharma (timalsina)',
    'tahir ali ansari',
    'taiyab husein',
    'taj mohammad miya',
    'tak bahadur gurung',
    'takashi miyahara',
    'tana gautam',
    'tank bahadur moktan',
    'tank dhakal',
    'tanka angbuhang limbu',
    'tanka badur darji',
    'tanka bahadur jirel',
    'tanka bahadur moktan',
    'tanka bahadur muktan',
    'tanka dhakal',
    'tanka karki',
    'tanka mani sharma',
    'tanka mani sharma (dangal)',
    'tanka prasad dhakal',
    'tanka prasad dhungana',
    'tanka prasad sharma',
    'tankamani sharma',
    'tap bahadur magar',
    'tapasi raya',
    'tapendra bahadur rawal',
    'tapiya kumari darai',
    'tapta bahadur bista',
    'tara bahadur kafle',
    'tara bahadur koirala',
    'tara devi bhatta',
    'tara devi joshi',
    'tara devi rai',
    'tara g.c.',
    'tara gharti',
    'tara gharti magar',
    'tara giri',
    'tara kanta chaudhary',
    'tara kumar khadka',
    'tara kumari gharti',
    'tara lama tamang',
    'tara man gurung',
    'tara narayan shrestha',
    'tara nath dahal',
    'tara nath luitel',
    'tara prasad bhattarai',
    'tara prasad pokharel',
    'tara prasad sapkota',
    'tara samyangya',
    'tara subba',
    'taradevi bhatta',
    'taraman gurung',
    'taraman swaar',
    'taranarayan shrestha',
    'taranath ranabhat',
    'tarani datta chataut',
    'tarka raj bhatta',
    'tarun bahadur gurung',
    'tashi tundup gurung',
    'tasi shangmo gurungseni/ tashi syangbo gurungseni',
    'tej bahadur basnet',
    'tej bahadur budhathoki',
    'tej bahadur dumrel',
    'tej bahadur karki',
    'tej bahadur kc',
    'tej bahadur mijar',
    'tej bahadur oli',
    'tej bahadur rai',
    'tej bahadur sinjali',
    'tej kumar ale',
    'tej kumari poudel',
    'tej narayan poudel',
    'tej narayan singh rai',
    'tej narayan yadav',
    'tej prasad chaudhary',
    'tejasbi thebe',
    'tejbahadur mijar',
    'tejbahadur oli',
    'tejendra prasad sharma',
    'tejkumari paudel',
    'tejman kandangawa',
    'tejraj pandey',
    'teju lal chaudhary',
    'tejulal chaudhari',
    'tek narayan kunwar',
    'tek bahadur basnet',
    'tek bahadur chokhyal',
    'tek bahadur gharti',
    'tek bahadur gurung',
    'tek bahadur moktan',
    'tek bahadur rai',
    'tek bahadur raika aauji',
    'tek bahadur rawal',
    'tek bahadur rokaya',
    'tek bahadur sarki',
    'tek bahadur thapa',
    'tek bahadur thapa gharti',
    'tek narayan poudel',
    'tek prasad dhungana',
    'tek raj joshi',
    'tek raj nepal',
    'tek raj pant',
    'tekbahadur balampakhi',
    'tekendra prasad bhatta',
    'teku nepali',
    'temba bhote',
    'temba gurung',
    'tendi sherpa lama',
    'thagendra prakash puri',
    'thagendra puri',
    'thaku mahato koiri',
    'thakur d.c',
    'thakur gaire',
    'thakur prasad baral',
    'thakur prasad dhakal',
    'thakur prasad sharma',
    'thakur prasad sharma poudel',
    'thakur singh tharu',
    'tham maya thapa',
    'tham maya thapa magar',
    'thamsara pun',
    'than kumari thapa',
    'thani yadav',
    'tharuhat tarai party nepal',
    'thir bahadur karki',
    'thok prashad sibakoti',
    'thomas gass',
    'tika bahadur hamal',
    'tika baldav sapkota',
    'tika dutta niraula',
    'tika prasad upreti',
    'tika ram acharya',
    'tika ram chaudhari',
    'tika ram chemjong limbu',
    'tika ram gurung',
    'tika ram pandey',
    'tika ram sahi',
    'tika ram sharma',
    'tikadatta niraula',
    'til bahadur bishwakarma',
    'til bahadur mahat chhetri',
    'til kumar menyanwo(limbu)',
    'til prasad shrestha',
    'tilak bahadur g.c',
    'tilak bahadur rawal',
    'tilak bahadur thapa',
    'tilak bahadur thapa magar',
    'tilak mahat',
    'tilak neupane',
    'tilak pariyar',
    'tilak prasad neupane',
    'tilak ram sharma',
    'tilakbahadur rawal',
    'tilakram sharma',
    'tilbahadur biswokarma',
    'tilkumar menyangbo',
    'tirha bahadur lama',
    'tirlokpratap rana',
    'tirth raj sapkota',
    'tirtha bahahdur lama',
    'tirtha gautam',
    'tirtha khanal',
    'tirtha man sakya',
    'tirtha raj dhakal',
    'tirtha raj kc',
    'tirtha raj khaniya',
    'tirthaman sakya',
    'tirtharaj chaudhary (bhaur)',
    'tirthraj dhakal',
    'tirthraj sharma',
    'tirudevi pal',
    'tok bahadur tamang',
    'toka ram chemjung limbu',
    'tomoo hozumi',
    'took raj sigdel',
    'top bahadur magar',
    'top bahadur oli',
    'top bahadur rayamajhi',
    'top bahadur singh',
    'top bhadur magar',
    'toran bahadur gurung',
    'tri ratna bajracharya',
    'trilochan bhatt',
    'trilochan bhatta',
    'trilochan pageni',
    'trilochan upreti',
    'trilok pratap rana',
    'triloki prasad',
    'tsetan gyurman shrestha,',
    'tsewang tenzen tamang',
    'tuk raj sigdel',
    'tukabhadraa hamal',
    'tul bahadur basnet',
    'tul bahadur gurung',
    'tul bahadur majhi',
    'tul bahadur shrestha',
    'tul bhadur gurung',
    'tula raj basyal',
    'tula ram gharti magar',
    'tularaj bista',
    'tularam bishta',
    'tulashi pd sitaula',
    'tulasi subba',
    'tulasi prasad chaudhary',
    'tulasi prasad sitaula',
    'tulasi ram aryal',
    'tulasi ram sapkota',
    'tulasi ram sedai',
    'tulbahadur gurung',
    'tulsa rana',
    'tulsi giri',
    'tulsi prasad neupane',
    'tulsi prasad sitaula',
    'tulsi thapa',
    'u nay win',
    'u tun nay lin',
    'ubjan bahadur shahi',
    'uday bdr. bohora',
    'uday chandra thakur',
    'uday kumar yadav',
    'uday narayan chaudhari',
    'uday prakash chapagain',
    'uday raj gauli',
    'uday raj pandey',
    'uday raj sapkota',
    'uday tiwari',
    'udaya chandra thakur',
    'udaya kumar barbariya yadav',
    'udaya nepali shrestha',
    'udaya prakash chapagain',
    'udaya rai',
    'udaya raj gauli',
    'udaya sharma (poudel)',
    'udaya sharma poudel',
    'udaya shumsher rana',
    'udayachandra thakur',
    'udayakanta mishra',
    'udayaraj upadhyaya',
    'udayraj sapkota',
    'uddhab prasad bastakoti',
    'uddhav poudel',
    'uddhav prasad kharel',
    'uddhav singh thapa',
    'uddhav thapa',
    'udhav thapa',
    'ujjwal prasad baral',
    'ukendra bahadur bohora',
    'uma adhikari regmi',
    'uma bhujel',
    'uma dahal',
    'uma gothe (kapali)',
    'uma kant sharma',
    'uma karki bista',
    'uma koirala',
    'uma kumari badi',
    'uma regmi',
    'uma shankar aragriya',
    'umakant jha',
    'umakant sharma',
    'umakanta chaudhary',
    'umakanta jha',
    'umashankar argariya',
    'umawati chaudhari',
    'umesh chandra jha',
    'umesh koirala',
    'umesh kumar ojha',
    'umesh kumar singh',
    'umesh kumar yadav',
    'umesh mainali',
    'umesh prasad bhatta',
    'umesh prasad luintel',
    'umesh prasad mainali',
    'umesh prasad thani',
    'umesh prasad yadav',
    'umesh raj paudel',
    'umesh shrestha',
    'umesh yadav',
    'umeshprasad mainali',
    'umita bishwokarma',
    'unnati bohora',
    'upama kumari dev',
    'upama kumari yadav',
    'upendra mahato',
    'upendra bahadur thapa',
    'upendra devkota',
    'upendra kant aryal',
    'upendra koirala',
    'upendra kumar koirala',
    'upendra lamsal',
    'upendra prasad gautam',
    'upendra prasad ghimire',
    'upendra prasad kushwaha',
    'upendra prasad yadav',
    'upendra subedi',
    'upendra yadav',
    'urba datta pant',
    'urmila thapa',
    'urmila aryal',
    'urmila debi bishwokarma',
    'urmila devi shah',
    'urmila devi yadav',
    'urmila mahato koiri',
    'urmila shrestha',
    'usa gurung',
    'usa kala rai',
    'usha yadav',
    'usha devi tharuni',
    'usha gurung',
    'usha jha',
    'usha kala rai',
    'usha kiran ansari',
    'usha kumari',
    'usha kumari pokhrel',
    'usha kumari yadav',
    'usha nepal',
    'usha rajbanshi',
    'usha rana',
    'ushakala rai',
    'uttam bahadur saud',
    'uttam banjara',
    'uttam bhattarai',
    'uttam kumar bhattarai',
    'uttam kumar karki',
    'uttam kumar lama',
    'uttam kumar sharma',
    'uttam mahat',
    'uttam prasad chapagin',
    'uttar kumar basnet',
    'uttar kumar khatri',
    'uttar kumar oli',
    'valerie julliand',
    'valerie julliand ( resident coordinator)',
    'valery v. nazarov',
    'ved narayan meheta',
    'veronica cody (head of delegation/ambassador)',
    'vesh raj sharma',
    'veshraj regmi',
    'vidhur kumar karki',
    'vidhya/bidhya devi bhandari',
    'vidyadhar mallik',
    'vidyut raj chalise',
    'vijay bahadur kunwar',
    'vijay kumar gachhdar',
    'vijay kumar saravagi',
    'vijay kumar vishwash',
    'vijay kumar yadav',
    'vijay rai',
    'vijay shankar prasad sah',
    'vijay shankar yadav',
    'vijay subedi',
    'vijay yokpangden',
    'vijaya bahadur kunwar',
    'vijaya chalise',
    'vijaya laxmi aryal',
    'vinod kc',
    'vinod kumar khadka',
    'vinod kumar yadav',
    'vipin rai',
    'virendra prasad singh',
    'virendra prasad yadav',
    'virsha bahadur rai',
    'vishal/bishal bhattarai',
    'vishant kumar vania',
    'visheshwar prasad ojha',
    'vishma raj angdembe',
    'vishnu kumar agarwal,',
    'vishnu om bade',
    'vishnu prasad lamsal',
    'vishnu prasad poudel',
    'vishnu/bishnu mani acharya',
    'vishwa nath goel',
    'vishwa prakash sharma',
    'vishwa/bishwa bhakta dulal',
    'vishwa/bishwa man shrestha',
    'vishwanath oli',
    'vishwendraman pashwan',
    'vn acharya',
    'waijnath kalwar',
    'wellage swarnalatha perera',
    'wenny kussum',
    'william c. cassell',
    'wimal de silva',
    'wise tamang',
    'wita kumari mahat',
    'wongdi sherpa',
    'wu congyong',
    'wu jianming',
    'yaam prasad dahal',
    'yadav',
    'yadav b. khapung',
    'yadav khanal',
    'yadav lal vaidya',
    'yadav prasad koirala',
    'yadav prasad pant',
    'yadav rai',
    'yadu bamsha jha',
    'yadu prasad lax',
    'yadubansa jha',
    'yaga raj sunuwar',
    'yagya bahadur bogati',
    'yagya bahadur budha chhetri',
    'yagya bahadur hamal',
    'yagya bahadur karki',
    'yagya bahadur thapa',
    'yagya prasad basyal',
    'yagya prasad gautam',
    'yagya raj bhatta',
    'yagya raj sunuwar',
    'yagyamurti banjade',
    'yagyaraj sunuwar',
    'yahun chandra sibakoti',
    'yak bahadur rana magar',
    'yak nath bastola',
    'yam bahadur charmakar',
    'yam bahadur malla',
    'yam bahadur nepali',
    'yam bahadur pariyar',
    'yam kumar anbohang',
    'yam kumari khatwada',
    'yam lal kadel',
    'yam nath dahal',
    'yamlal pokhrel',
    'yamuna bhattarai',
    'yangjing bista',
    'yangkila sherpa',
    'yaron yitzchak mayer',
    'yashoda adhikari',
    'yashoda gurung subedi',
    'yashoda kumari lama',
    'yashodadevi adhikari',
    'yashwant kumar singh',
    'yasodha adhikari',
    'yek narayan sharma',
    'yesoda kumari lama',
    'yob raj bhusal',
    'yobindra singh tamang',
    'yog narayan yadav',
    'yog raj baral',
    'yog raj limbu',
    'yog raj pokharel',
    'yogendra chaudhari',
    'yogendra dhakal',
    'yogendra kumar karki',
    'yogendra kumar shrestha',
    'yogendra pajiyar',
    'yogendra prasad chaudhary',
    'yogendra pujiyar',
    'yogendra rae yadav',
    'yogendra rai yadav',
    'yogendra raj sangaula',
    'yogendra ray yadav',
    'yogendra sharma sutihar',
    'yogendra thakur',
    'yogesh bhattarai',
    'yogesh kumar bhattarai',
    'yogeshwor parajuli',
    'yoodah shah',
    'yousef haider murad',
    'yousef mohammed al-hail',
    'yousif bin mohamed al-hail',
    'yu hong',
    'yub kumar paudel',
    'yuba nath lamsal',
    'yuba raj bhusal',
    'yuba raj dulal',
    'yuba raj gyawali',
    'yuba raj karki',
    'yuba raj khatiwada',
    'yuba raj pandey',
    'yuba raj sangraula',
    'yuba raj subedi',
    'yubak dhoj g.c.',
    'yubaraj bhusal',
    'yubaraj chaulagain',
    'yubaraj gyanwali',
    'yubaraj khatiwada',
    'yubaraj kunwar',
    'yubraj bhattarai',
    'yubraj dulal',
    'yubraj jung shah',
    'yubraj paudel',
    'yubraj sharma',
    'yudhistir khadka',
    'yudubansha jha',
    'yutul lama',
    'yuv raj lawati',
    'yuvaraj dulal',
    'yuvaraj gautam',
    'yuvaraj karki',
    'yuvaraj khatiwada/ yuva raj khatiwada',
    'yuvraj karki',
    'yuvraj khanal',
    'yuvraj pandey',
    'yuvraj subedi',
    'yuwak dhoj g.c',
    'yuwaraj gyawali',
    'yves carmona',
    'zengi kaminaga',
    'aakash limbhu',
    'aani chhoeng dolma',
    'bikash bahadur chhetri',
    'bikash karki',
    'bindu kumar singh',
    'bishal magar',
    'dalbahadur kumal',
    'devaki nandan kasodhan',
    'dhanbir bhagat',
    'dhubra mahato',
    'giriraj koirala',
    'jaynath chauwe',
    'kameshwar shah kalwar',
    'khemraj bk',
    'krishna darnal bishwakarma',
    'mohammad raphik aalam',
    'mohmda chhatu minya',
    'nabin kumar chaudhary',
    'nasiv tamang',
    'nurjaha khatun',
    'pasang tamang',
    'raju swarnakar',
    'ramesh bahadur pandey',
    'ramprasad sah',
    'roshan shah',
    'sahdev kumar',
    'satosh khanal',
    'sujan shanker',
    'sujan thapa bhanne minbahadur kumal',
    'sushil pandey',
    'tara shrestha',
    'tiyago mendas perira',
    'uday giri',
    'uma shrestha',
    'william camron',
    ' bajru gangai',
    ' chandraprasad gangai',
    ' himal bhanine saagar kedem ',
    ' kisan chhantyal',
    ' suman bala',
    'aaiti bista',
    'aanju bishta',
    'aashish thapamagar',
    'abbash miya',
    'abdulla dewan',
    'abhimanyu yadav',
    'abhinash lama',
    'abhinash yadav',
    'abhisekh tamang',
    'abilal bista',
    'abinash kunwar',
    'abinash pandit',
    'achaya haridas',
    'ajaykumar pathak',
    'ajit pratap singh',
    'ajitpratap singh',
    'akash shrestha',
    'akilesh kanu',
    'alan kumar rokamagar',
    'aman kumar sah',
    'amar singh rai',
    'amir shakya',
    'amit kumar',
    'amit kumar sahani',
    'amit yadav',
    'ammar bahadur darae',
    'amrita karki',
    'anil bk',
    'anil tamang',
    'anil thapa',
    'anish kumar',
    'anjana sah',
    'anmol pudasaini',
    'anuj rungata',
    'anumudin ansari',
    'anup lama',
    'archana gupta',
    'arjun khatri',
    'arjun raut',
    'arjun shahi',
    'arjun thapa magar',
    'arun sawarthiya',
    'ashish ghimire',
    'ashish sripali',
    'ashok bhanne ashish rai',
    'ashok lama',
    'baba tamang',
    'bablu kumar yadav',
    'bablu paswan',
    'babu raja shakya',
    'babu shrestha',
    'baburam lamichhane',
    'baburam tamang',
    'badri bhandari',
    'badribahadur thapa',
    'baijnath sah teli',
    'bajarangi',
    'bakhan tamang',
    'bal bahadur budha',
    'bal krishna shrestha',
    'bal kumar limbu',
    'baliram mahato',
    'balram katuwal',
    'bandu kumar singh',
    'barshat tamang',
    'basant tamang',
    'bashanta babu shrestha',
    'basudev mainali',
    'beni kale bhanine kumar darji (pariyar)',
    'bhadra bahadur kami',
    'bhakta bahadur pandey',
    'bharat yadav',
    'bharthari dagaura',
    'bhim bahadur rawat',
    'bhim bahadur sunar',
    'bhim k.c.',
    'bhimbahadur tamang',
    'bhimlal shrestha',
    'bhogendra shah',
    'bhoj bahadur bam',
    'bhola yadav',
    'bholanath chalise',
    'bhup bahadur roka ',
    'bibek basnet',
    'bigesh rai',
    'bihari sah',
    'bijay bharati',
    'bijay kumar chaudhary',
    'bijay kumar mahara',
    'bijay kumar paswan',
    'bijay yadav',
    'bijaynath chaubey',
    'bikash bhanne kamal rokka',
    'bikash bholan',
    'bikash bk',
    'bikash chaudhary',
    'bikash kumar gupta',
    'bikash shrestha',
    'bikash subedi',
    'bikash tamang',
    'bikendra chaudhary',
    'bikram mestar',
    'bimal magar',
    'binay bhanne chandrakanta tharu chaudhary',
    'binay sah',
    'binay seshwali',
    'binod er',
    'binod harijan',
    'binod khadgi',
    'binod kumar shreebastav',
    'binod pradhan',
    'binod prasad kanu',
    'bipendraraj batas',
    'bir bahadur khadka',
    'bir bahadur nepali',
    'bir narayan chaurasiya',
    'birendar prasad yadav',
    'biru chaudhary',
    'bishal gurung',
    'bishal ranjit',
    'bishal shrestha',
    'bishal tamang',
    'bishnu shrestha',
    'bishun pratap sah',
    'bishwaraj sharma',
    'bishwashwar prasad shah',
    'bisombhar yadav',
    'biswas gurung',
    'bitu bhanne genish gurung',
    'bramhadev mahato',
    'brij kishor yadav',
    'brijkishor kumar',
    'buddha bahadur rajali',
    'buddharaj thebey',
    'buddhi prasad dahal',
    'buddhi tamang',
    'budey lama',
    'chakra bahadur razi',
    'chakra thakulla',
    'chandan kumar amatya',
    'chandra bahadur gharti',
    'chandra khadka',
    'chandra man shrestha',
    'chaturman limbu',
    'chering dhawa gurung',
    'chet bahadur shrestha',
    'chhedilala sah sonar',
    'chhering gyalzen sherma',
    'chija basnet',
    'chiring dawa gurung',
    'chitranjan prasad',
    'dalla bhanne mastadin miya',
    'dambar bahadur khatri',
    'dawa chiring tamang',
    'debendra yadav',
    'debit singh er',
    'deelip shah',
    'deepak mahato',
    'deepak singh badal',
    'deependra kumar dev',
    'deepkumar barma',
    'denial bhanne anil',
    'dev bahadur oli',
    'dev bhanne kotbahadur tamang',
    'dev kumar shrestha',
    'dev kumar thapa',
    'dev narayan thakur',
    'devkrishna khadga yadav',
    'devlal kapada',
    'dhak bahadur karki',
    'dhan bahadur malla',
    'dhanaji saheb rawa wawar',
    'dhankamal gurung',
    'dhankeshar rai',
    'dharma singh ghising',
    'dhawa thapa',
    'dhiraj kumar thapa',
    'dil bahadur khatri',
    'dil bahadur lyo',
    'dilap damai',
    'dilli bahadur rai',
    'dilli prasad acharya',
    'dinesh gharti',
    'dinesh pradhan',
    'dinesh sukubhatu',
    'dinesh thapamagar',
    'dipa kandel',
    'dipak adhikari',
    'dipak budha',
    'dipak khatri',
    'dipak kumar karna',
    'dipak nepali',
    'dipak thapa gurung',
    'dipen biswakarma',
    'dipendra kumar mandal',
    'dipendra saud',
    'dipendra thakur',
    'dipendra yadav',
    'dolbahadur karki(db)',
    'durga prasad paudel',
    'ekendra bahadur khadka',
    'ekendra shahi',
    'ekramodin',
    'eliyas miya ansari',
    'farestardaya bahadur kc',
    'gamhira sah teli',
    'ganeru majhi',
    'ganesh chaudhary',
    'ganesh ghale',
    'ganesh kc',
    'ganesh kumar gupta',
    'ganesh paswan',
    'ganesh sunar',
    'ganesh thapa',
    'ganga lingden limbu',
    'gangaram shrestha',
    'gauri shankar yadav',
    'ghanshyam sah',
    'ghanshyam shrestha',
    'gita kumari panthi',
    'gokarna mahato',
    'gokarna thapa',
    'gopal khadka',
    'gopal shiwakoti',
    'govinda pariyar',
    'govinda tamang',
    'govinda yadav',
    'gulabh khan',
    'guru jit',
    'guru prasad chaudhary',
    'gyanendra gautam',
    'hari bahadur raskoti',
    'hari gopal acharya',
    'hari khadka bhanne harisharan khadka',
    'hari kumar chand',
    'hari neupane',
    'hari prasad chaudhary',
    'harinath adhikari',
    'hariram ale',
    'harish chandra kumar',
    'harjeet singh',
    'harka bahadur blon',
    'harun rasid',
    'hem bahadur bastakoti',
    'hikmat miya',
    'hira mukhiya',
    'hom bahadur gurung',
    'hom gurung',
    'hridayaraj bajagai',
    'ijahir hawari',
    'indra bahadur putuwar',
    'indra kumar tamang',
    'indra man tamang',
    'indra prasad chaudhary',
    'ishaq dhungana',
    'ishwar karki',
    'jafar miya',
    'jafir aalam',
    'jagadish prasad shah',
    'jagdish sariya',
    'jagir aansari',
    'jambil miya',
    'jamil akhtar',
    'jamirdin miya',
    'janga bahadur rana',
    'janju bhanne saiman shrestha',
    'janma adhikari',
    'javed aalam',
    'javed hussain',
    'jay bahadur muktan',
    'jay prakash sah',
    'jay prakash yadav',
    'jayram khatri',
    'jayram pun',
    'jeet bahadur budha',
    'jeet bahadur shrestha',
    'jeevan gurung',
    'jenish rai',
    'jenraj bhanne jangali shahi',
    'jhyampa chuldim lama',
    'jhyampachuldim lama',
    'jisan sunwar',
    'jitendra kimar mahato',
    'jitendra sah',
    'jiyalal mahato',
    'kaelash mantachhe shrestha',
    'kailash matache shrestha',
    'kailash rokaya',
    'kaiyum raym',
    'kaliman budha',
    'kalu rana',
    'kamal bk',
    'kamal gurung',
    'kamal mahato koiri',
    'kamal sitauala हरीप्रसाद चौधरी',
    'kamal sitaula',
    'kanchha bhandari',
    'kanchi maya ghale',
    'karma gurung',
    'karma tasi joshi',
    'karna jeet budha',
    'karnaprasad nepali',
    'kedar rai',
    'kedarnath dhakal',
    'kedarnath parajuli',
    'keshar singh gharti',
    'keshav bahadur khadka',
    'keshav bahadur oli',
    'keshav sunar',
    'khadak singh kathayat',
    'khadga bahadur bhujel',
    'khagendra bam bhanne khagendra rajwar',
    'khagendra bhattarai',
    'kham bahadur gurbhuja',
    'khetnath ghimire',
    'khim bahadur',
    'khuram dagauda',
    'kiran ghale',
    'kiran shrestha ',
    'kishan sapkota',
    'krishna bahadur dahal',
    'krishna bahadur khatri',
    'krishna bhandari',
    'krishna prasad tamrakar',
    'krishna prasad timalsina',
    'krishna yadav',
    'kumar bahadur rajbhandari',
    'kumar mahatara',
    'kumar majhi',
    'kumar thakuri',
    'kumsingh ghising',
    'kunal kumar',
    'kunjan bihari prasad chaudhary',
    'laddu sah',
    'lainasila sanjel',
    'lakchhu lohar',
    'lakpa sherpa',
    'lakshya panta',
    'lal babu prasad sah',
    'lal babu raya',
    'lal bahadur chaudhary',
    'lal bahadur ghising',
    'lal bahadur oli',
    'lal bahadur raya',
    'lal maya budha',
    'lal mohammad gaddhi',
    'lalbabu raya',
    'lambodar nyaupane',
    'laxman bhanne tronkumar thapa',
    'laxman chandra',
    'laxman prasad sharma',
    'laxman syangtan',
    'laxman tiruwa',
    'laxmi prasad sah',
    'laxmi shahi',
    'lee ning ja',
    'lee siyaoophing',
    'lekhnath sharma',
    'lekhnath upadhyay',
    'lila dangi',
    'lok bahadur gurung',
    'lokendra badhu',
    'lokendra budha',
    'lokesh khatri',
    'madan adhikari',
    'madan bahadur malla',
    'madan jung sah',
    'madan kumar lal karna',
    'madan kumar malla',
    'madhav thapa',
    'madhu mahat',
    'mahammad noor kha',
    'mahendra pal',
    'mahendra pradhan',
    'mahesh yonjan',
    'man bahadur khatri',
    'man bahadur rana',
    'manbahadur oli',
    'mangal shahi',
    'mangal singh limbu',
    'manir miya',
    'manish',
    'manish kumar gupta',
    'manish lama',
    'manju chaudhary khadka',
    'manoj kumar khotwe',
    'manoj kumar kuswah',
    'manoj kumar sah',
    'manoj magar',
    'manoj shrestha',
    'manoj singh bista',
    'manowat musahar',
    'markel guli',
    'meghraj kafle',
    'meroj khan',
    'mewa bhanne chandra bahadur ghalan',
    'milan rai',
    'milan silwal',
    'mina devi sah',
    'mina ram',
    'minbahadur magar',
    'minbahadur phago',
    'minya',
    'mishri sah kanu',
    'mohamda amir minya',
    'mohammad afroz',
    'mohammad ali',
    'mohammad amirul',
    'mohammad apharoj',
    'mohammad farid',
    'mohammad hakim',
    'mohammad kaeyum',
    'mohammad rahaman',
    'mohammad riyaaj',
    'mohammad riyaz raym',
    'mohammad sakil',
    'mohammad sakim hussain',
    'mohammad sanaullah kha',
    'mohan bohara',
    'mohanraj sharma',
    'mokhtar ahamat',
    'mon bohara',
    'mukesh',
    'mukesh chaurasiya',
    'mukesh yadav',
    'mukunda bhandari',
    'mukunda kc',
    'murfa balara',
    'nabin chand',
    'nabin kandel',
    'nabin rai',
    'nabin shrestha',
    'naendra paruhang rai',
    'naimodin dewwang',
    'nakki bhanne bijay mahato',
    'nakul patel',
    'nanda bahadur',
    'narayan bahadur shrestha',
    'narayan bahadur sunar',
    'narayan budathoki',
    'narayan das',
    'narayan lamsal',
    'narayan thapamagar',
    'narendra bishwakarma',
    'naresh gharti',
    'naresh lama',
    'naresh mahato',
    'naresh man singh amatya',
    'narraj pandey',
    'nasir hussain',
    'navaraj thapa',
    'nawaraj gautam',
    'nawraj pandey bhanne ramraj siwakoti',
    'nim bahadur bhanari',
    'niraj kumar chaudhary',
    'niranjan bhattarai',
    'niranjan kumar agrawal',
    'niranjan tripathi',
    'nirjan khadka',
    'nirmal singh thakuri',
    'nischal bhanne ganesh dhakal',
    'nisha sah',
    'nishan rijal',
    'nitu chamar',
    'nok bahadur roka',
    'om bahadur karki',
    'om bahadur kunwar chhetri',
    'om prakash',
    'om prakash rai',
    'om prasad dotel',
    'omnath devkota',
    'orab chatarji',
    'pabitra kumar khadka',
    'padam bahadur budha',
    'padam thakuri',
    'padam thapa',
    'pahadi tharu',
    'pallav raj bhatta',
    'panta bahadur pun',
    'pappu kumar das',
    'pappu mehta',
    'parshuram nyaupane',
    'pasang lama',
    'pasang lundup gurung',
    'pashupati bhanne jeevan tamang',
    'pashupati chaudhary',
    'passang lama',
    'pinki chamar',
    'pom bahadur kunwar',
    'poshan panthi',
    'prabhakar upadhya',
    'prabhu giri',
    'prabin kumar pandey',
    'prabin rai',
    'prabin samrab fadam',
    'prabin waiba',
    'prajwol tamrakar',
    'prakash budha',
    'prakash darai',
    'prakash das',
    'prakash paudel',
    'prakash rajbamshi',
    'pramod mehta',
    'pramod yadav',
    'pravu giri',
    'prem bahadur b.k.',
    'prem lama',
    'prithibi bahadur sharma',
    'prithivi oli',
    'priti chamar',
    'prkash adhikari',
    'puja chamar',
    'purna bahadur thapa',
    'puspa gurung',
    'puspa paras rai',
    'rabi panta',
    'rabin gurung',
    'rabin thapa',
    'rabindra chokhani',
    'rabindra kumar',
    'rabindra yanjan',
    'rahul bhanne jivas sah',
    'rahul kumar raut',
    'rahul magar',
    'rahul raya agrawal',
    'raj bahadur chand',
    'raj giri',
    'raj kumar mandal',
    'raj kumar tamang',
    'raj kumari shahi',
    'rajan bishwakarma',
    'rajendra bishwakarma',
    'rajendra goley',
    'rajendra prasad luitel',
    'rajesh heda',
    'rajesh kumarv sah',
    'rajesh paswan',
    'rajib chhetri bhanne amar khadka',
    'rajju khadka',
    'rajkumar adhikari',
    'rajkumar chaudhary',
    'rajkumar pandey',
    'rajkumar rauniyar',
    'rajkumar siganchi',
    'raju bhanne raj kumar rai',
    'raju bk',
    'raju gorkhali',
    'raju karki',
    'raju kumar syangtan',
    'raju rai',
    'raju swarnkar',
    'rakesh kumar',
    'rakesh kumar chaurasiya',
    'rakesh shrestha',
    'ram balak prasad bin',
    'ram chandar oli pun',
    'ram karan jat',
    'ram krishna raut',
    'ram kumar moktan',
    'ram lal hirachan',
    'ram narayan sharma',
    'ram naresh sah',
    'ram prabesh rana',
    'ram sharan gautam',
    'ram tiwari',
    'ramagya prasad sah',
    'ramananda chaudhary',
    'rambabu chaudhary',
    'ramchandra mahato',
    'ramdayal sah',
    'ramdev rimal',
    'ramesh kaliraj',
    'ramesh kumar moktan',
    'ramesh kumar oli',
    'ramesh malla',
    'ramesh pandey',
    'ramesh pariyar',
    'ramesh tamang',
    'ramesh thapa magar',
    'rameshwor sah',
    'ramji babu yadav',
    'ramji ghale',
    'ramji rijal',
    'ramprakash satara',
    'ramprasad dhungana',
    'ramraj siwakoti',
    'ramraj yadav',
    'ramu yadav',
    'ranabahadur b.k.',
    'ranger jagbir khatri',
    'ranjan tripathi',
    'ranjit yadav',
    'rashmi ghimire',
    'reji sherpa',
    'reshami dagaura',
    'rishi subedi',
    'rishiram dhakal',
    'ritthe darji',
    'ritu fiyak limbu',
    'rohit kesari',
    'roshan gurung',
    'rrameshwor purvey bhanne rameshwor sah',
    'rudramani gharti',
    'ruth tolangee',
    'sabin mahat',
    'sachin chaudhary',
    'sachindra kumar kapar',
    'safikul rahaman',
    'safiul raen',
    'sagar sunar',
    'sahadeb pandit',
    'sahadev rai',
    'sahdev mahato',
    'sahil miya bhanne narul hak',
    'sajan bk',
    'sajan thapa',
    'salman khan',
    'samim safi',
    'samir shrestha',
    'samit ansari',
    'samrat sapkota',
    'samrat tamang',
    'samsudhin ansari',
    'sanam rai',
    'sanchita gurung',
    'sandeep pun',
    'saney bhanne hasta bahadur limbu',
    'sanjay kumar thakur',
    'sanjay rana',
    'sanjay sah',
    'sanjay sahani',
    'sanjay shamsher',
    'sanjeet basnet',
    'santa kumar moktan',
    'santidevi nuniya',
    'santosh bk',
    'santosh kandel',
    'santosh kumar limbu',
    'santosh kumar yadav',
    'santosh mahato',
    'santosh pun',
    'santosh rai',
    'santosh yadav',
    'sanu bhanne tolman gurung',
    'saraswati balami',
    'sarin shankar shrestha',
    'sarita kumari rana',
    'saroj kumar yadav',
    'sashi ram pun',
    'satyendra singh beghal',
    'saurav kumar',
    'sawa maila bhanne chaturman limbu',
    'shakti hirachan',
    'shakti kapoor paswan',
    'shaktiram wali',
    'shambhu',
    'shambhu kumar sah',
    'shambhu lal miya',
    'shambhu mahatraj',
    'shambhu prasad patel',
    'shambhu sah',
    'shambhu sahani',
    'shamila limbu',
    'shankar raut',
    'shankar tamang',
    'shanti tamang',
    'sharmila limbu',
    'sharmila magar',
    'shashank malla',
    'shaubhagya shahi',
    'sher bahadur gc',
    'shiva hari dhakal',
    'shiva kumar sangtani',
    'shiva prasad dahal',
    'shiva shankar yadav',
    'shivaraj pantha',
    'shreeram mahato guro',
    'shubham ghimire',
    'shukraram goley',
    'shyam bahadur majhi',
    'shyam krishna chwamu shrestha',
    'shyam kumar yadav',
    'shyam sundar yadav',
    'shyambhu prasad patel',
    'siddhartha chaudhary',
    'singhbahadur kuwar',
    'sitaram rimal',
    'sombahadur gole',
    'sonali sah',
    'sonam bhanne nemjung tamang',
    'sonam dhakpa gurung',
    'soni chamar',
    'subhas koirala',
    'sudhir karki',
    'sudip thakuri',
    'sujan darai',
    'sujan magar',
    'sukdev giri',
    'suklal tamang',
    'suku bhanne raj banmala',
    'sukuram tamag',
    'suman bahadur chaudhary',
    'suman bhandari',
    'suman shrestha',
    'sumit bhanne sumir bamjan',
    'sumit sah',
    'sundar khadka',
    'sundar rana',
    'sunil alemagar',
    'sunil chaudhary',
    'sunil khadka chhetri',
    'sunil kumar',
    'sunil kumar mandal',
    'sunil pandit',
    'suraj gyawali',
    'suraj thakur',
    'suraj tiruwa',
    'surendra shahi',
    'suresh chandra dc',
    'suresh magar',
    'suresh mahato',
    'suresh majhi',
    'suresh prasad das',
    'surya bhujel',
    'surya tamang',
    'susan jc',
    'sushil mandal',
    'suwas baniya',
    'suwas pradhan',
    'tahir ali',
    'tanka bhujel',
    'tanka prasad sanjel (upadhyay)',
    'tanka prasad upadhya',
    'tara bahadur pun',
    'tara budhamagar',
    'tara kumar shrestha',
    'tara prasad rana',
    'tara shahi',
    'taradevi gurung',
    'tarahang rai',
    'tashi sherpa',
    'tejendra basnet',
    'tek bahadur kumal',
    'tek bahadur tamang',
    'thengwa bhanne ramesh mandal',
    'tilak chaudhary',
    'tilak oli',
    'tilakram adhikari',
    'top bahadur mahatara',
    'tulsi prasad timalsina',
    'turunta lal badahi',
    'uday mukhiya',
    'uddhav prasad nepal',
    'udra prasad adhikari',
    'ugranath jha',
    'ugrasen rana',
    'ujjwal sharma',
    'ukren pasang gurung',
    'umesh khatri',
    'umesh majhi',
    'umesh mandal',
    'umesh raj poudel',
    'umesh sherchan',
    'upa bahadur gaha magar',
    'upendra timalsina',
    'urken passang',
    'uttam lal sah',
    'varn bahadur singh',
    'yam bahadur katwal',
    'yamuna kc bhanne alisha khatri',
    'yogendra gurung',
    'yogendramani dahal',
    'yubin gc',
    'yubraj gurung',
    'yuvaraj bk',
    'yuvaraj giri',
    'yuwaraj paswan',
]

let results  = [];
let fromto   = process.argv.pop()
let from     = fromto.split('-')[0]
let to       = fromto.split('-')[1]
let total    = to - from;
let averages = [];

fs.readFile('list.txt', 'utf8', function(err, file_contents) {

    const list = uniq(file_contents.split('|'));

    uniq(words).splice(from,total).map((name, i)=>{
        let start = new Date();

        i = i + 1

        let similar_words = list.map((e)=>{

            let percentage = fuzz.ratio(e, name)

            if(percentage > 98) {

                return { name, similar_name: e, percentage }
            }

            return null;

        }).filter(Boolean)

        if(similar_words.length > 0) {
            results = results.concat(similar_words)
        }

        if(results) {

            if(i%10 == 0) {
                let xls = json2xls(results)

                fs.writeFileSync(fromto+'.xlsx', xls, 'binary', function (err) {
                        console.log(err)
                });
            }


            let end = new Date()

            let estimate = Math.round(end-start);

            if(averages.length > 20) {
                averages.shift()
            }

            averages.push(estimate)

            let remaining_time = humanizeDuration(mean(averages) * (total - i), {round:true})

            process.stdout.write('\033c');

            console.log('Finished Processing ' + i +' items')

            console.log('Remaining Time: ' + remaining_time)

        }

        if(total == i) {

            let xls = json2xls(results)

            fs.writeFileSync(fromto+'.xlsx', xls, 'binary', function (err) {
                    console.log(err)
            });

            process.stdout.write('\033c');
            console.log('Finished')
        }

    });

});